project:
  type: website
  output-dir: docs
  
website:
  title: "R Class Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: 
      - icon: github
        href: https://github.com/RekaIv/myactualwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Reka Ivanyi"

format:
  html:
    theme: cerulean
    toc: true

editor: source

